[package]
name = "game-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { "version" = "1.13.1", "features" = ["derive"] } 
ecs = "0.23.1"
pollster = "0.3.0"
wgpu = "0.15.1"
winit = "0.28.2"
